# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2970f478ef904983880a2c0571b65ebcc132d2cf598106627d1a48f7b460ee29773ea3f3d278696cb2135ae86bce5511e1491bee7d23da2707cc4572a7f5f20
  lol_api_key: 466ee1ca-6789-48c9-b705-356d45ff53e6

test:
  secret_key_base: 22d6dad11f38e38272d2baf308b6ad00488dba35e6a18227895866086271a7f03305d06d75135004f1ae71fbdbcde21869dd07c8e489563e9aa22ee38cf5d3fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  lol_api_key: 466ee1ca-6789-48c9-b705-356d45ff53e6
